# Generated by Django 4.1.1 on 2022-09-27 14:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='programme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.programme'),
            preserve_default=False,
        ),
    ]
