# Generated by Django 4.1.1 on 2022-09-29 13:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_video_image_remove_video_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.department'),
            preserve_default=False,
        ),
    ]
