# Generated by Django 4.1.1 on 2022-09-27 14:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_faculty'),
        ('user', '0002_remove_user_staff_choice_user_is_moderator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.department'),
            preserve_default=False,
        ),
    ]
